Repository AntAlbum/backend, pull requests merged in 2023-05, with the labels that each got.

#3 refactor: resetting spring boot project
  .gitignore
  BE/build.gradle.kts
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle.kts
  BE/src/main/java/ssafy/antalbum/be/BeApplication.java
  BE/src/main/java/ssafy/antalbum/be/Hello.java
  BE/src/main/java/ssafy/antalbum/be/HelloController.java
  BE/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/spy.properties
  BE/src/main/resources/static/index.html
  BE/src/main/resources/templates/hello.html
  BE/src/test/java/ssafy/antalbum/be/BeApplicationTests.java
Labels: 🛠 Refactor

#5 Refactor/package naming
  BE/settings.gradle.kts
  be/build.gradle.kts
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle.kts
  be/src/main/java/ssafy/antalbum/AntalbumApplication.java
  be/src/main/java/ssafy/antalbum/Hello.java
  be/src/main/java/ssafy/antalbum/HelloController.java
  be/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  be/src/main/resources/application.yml
  be/src/main/resources/spy.properties
  be/src/main/resources/static/index.html
  be/src/main/resources/templates/hello.html
  be/src/test/java/ssafy/antalbum/AntalbumApplicationTests.java
Labels: 🚑 Fix, 🛠 Refactor

#13 Feature/apply s3
  be/build.gradle.kts
  be/src/main/java/ssafy/antalbum/conf/AmazonConfig.java
  be/src/main/java/ssafy/antalbum/conf/SpringSecurityConfig.java
  be/src/main/java/ssafy/antalbum/controller/DashboardController.java
  be/src/main/java/ssafy/antalbum/entity/FileMeta.java
  be/src/main/java/ssafy/antalbum/repository/FileMetaRepository.java
  be/src/main/java/ssafy/antalbum/service/AmazonS3Service.java
  be/src/main/java/ssafy/antalbum/service/AmazonS3ServiceImpl.java
  be/src/main/java/ssafy/antalbum/service/MetadataService.java
  be/src/main/java/ssafy/antalbum/service/MetadataServiceImpl.java
  be/src/main/java/ssafy/antalbum/util/MetadataExtractor.java
  be/src/main/resources/application.yml
  be/src/main/resources/templates/dashboard.html
Labels: ✨ Feat

#14 Feature/entity development
  .gitignore
  be/src/main/java/ssafy/antalbum/entity/adventure/Adventure.java
  be/src/main/java/ssafy/antalbum/entity/adventure/AdventureDate.java
  be/src/main/java/ssafy/antalbum/entity/adventure/AdventureLocation.java
  be/src/main/java/ssafy/antalbum/entity/comment/Comment.java
  be/src/main/java/ssafy/antalbum/entity/comment/CommentDate.java
  be/src/main/java/ssafy/antalbum/entity/comment/CommentLocation.java
  be/src/main/java/ssafy/antalbum/entity/like/Like.java
  be/src/main/java/ssafy/antalbum/entity/like/LikeDate.java
  be/src/main/java/ssafy/antalbum/entity/like/LikeLocation.java
  be/src/main/java/ssafy/antalbum/entity/like/LikeStatus.java
  be/src/main/java/ssafy/antalbum/entity/photo/FileMeta.java
  be/src/main/java/ssafy/antalbum/entity/photo/Metadata.java
  be/src/main/java/ssafy/antalbum/entity/photo/Photo.java
  be/src/main/java/ssafy/antalbum/entity/tag/Tag.java
  be/src/main/java/ssafy/antalbum/entity/tag/TagStatus.java
  be/src/main/java/ssafy/antalbum/entity/travel/Travel.java
  be/src/main/java/ssafy/antalbum/entity/travel/TravelStatus.java
  be/src/main/java/ssafy/antalbum/entity/user/Friend.java
  be/src/main/java/ssafy/antalbum/entity/user/FriendStatus.java
  be/src/main/java/ssafy/antalbum/entity/user/User.java
  be/src/main/java/ssafy/antalbum/entity/user/UserInfo.java
  be/src/main/java/ssafy/antalbum/entity/user/UserStatus.java
  be/src/main/java/ssafy/antalbum/repository/FileMetaRepository.java
  be/src/main/java/ssafy/antalbum/service/MetadataService.java
  be/src/main/java/ssafy/antalbum/service/MetadataServiceImpl.java
  be/src/main/resources/application.yml
Labels: ✨ Feat

#20 Feature: attraction domain / Fix : querydsl setting (#9)
  be/build.gradle
  be/src/main/java/ssafy/antalbum/conf/QuerydslConfig.java
  be/src/main/java/ssafy/antalbum/domain/attraction/controller/AttractionController.java
  be/src/main/java/ssafy/antalbum/domain/attraction/dto/SearchCondition.java
  be/src/main/java/ssafy/antalbum/domain/attraction/entity/Attraction.java
  be/src/main/java/ssafy/antalbum/domain/attraction/entity/Sido.java
  be/src/main/java/ssafy/antalbum/domain/attraction/repository/AttractionRepositoryCustom.java
  be/src/main/java/ssafy/antalbum/domain/attraction/repository/AttractionRepositoryCustomImpl.java
  be/src/main/java/ssafy/antalbum/domain/attraction/repository/AttractionRepositsory.java
  be/src/main/java/ssafy/antalbum/domain/attraction/service/AttractionService.java
Labels: ✨ Feat

#21 Feature/entity setting
  be/src/main/java/ssafy/antalbum/entity/adventure/Adventure.java
  be/src/main/java/ssafy/antalbum/entity/comment/Comment.java
  be/src/main/java/ssafy/antalbum/entity/comment/CommentDate.java
  be/src/main/java/ssafy/antalbum/entity/comment/CommentLocation.java
  be/src/main/java/ssafy/antalbum/entity/like/Like.java
  be/src/main/java/ssafy/antalbum/entity/like/LikeDate.java
  be/src/main/java/ssafy/antalbum/entity/like/LikeLocation.java
  be/src/main/java/ssafy/antalbum/entity/photo/Photo.java
  be/src/main/java/ssafy/antalbum/entity/travel/Travel.java
  be/src/main/java/ssafy/antalbum/entity/user/Friend.java
  be/src/main/java/ssafy/antalbum/entity/user/User.java
Labels: ✨ Feat

#26 Swagger 추가
  be/build.gradle
Labels: ✨ Feat, 🕹 Test

#33 사용자 여행 리스트 보기
  be/src/main/java/ssafy/antalbum/controller/TravelAPIController.java
  be/src/main/java/ssafy/antalbum/dto/CreateTravelInfoRequest.java
  be/src/main/java/ssafy/antalbum/dto/CreateTravelInfoResponse.java
  be/src/main/java/ssafy/antalbum/dto/MemberDto.java
  be/src/main/java/ssafy/antalbum/dto/TravelDto.java
  be/src/main/java/ssafy/antalbum/entity/photo/Photo.java
  be/src/main/java/ssafy/antalbum/entity/photo/PhotoMeta.java
  be/src/main/java/ssafy/antalbum/entity/photo/PhotoPath.java
  be/src/main/java/ssafy/antalbum/entity/tag/Tag.java
  be/src/main/java/ssafy/antalbum/entity/travel/Travel.java
  be/src/main/java/ssafy/antalbum/repository/TravelRepository.java
  be/src/main/java/ssafy/antalbum/service/AmazonS3Service.java
  be/src/main/java/ssafy/antalbum/service/TravelService.java
  be/src/main/java/ssafy/antalbum/util/PhotoUtil.java
Labels: ✨ Feat

#36 여행 상세보기 구현
  be/src/main/java/ssafy/antalbum/controller/TravelAPIController.java
  be/src/main/java/ssafy/antalbum/dto/AdventureDto.java
  be/src/main/java/ssafy/antalbum/dto/FriendDto.java
  be/src/main/java/ssafy/antalbum/dto/TravelDetailDto.java
  be/src/main/java/ssafy/antalbum/dto/TravelDto.java
  be/src/main/java/ssafy/antalbum/entity/adventure/Adventure.java
  be/src/main/java/ssafy/antalbum/entity/adventure/AdventureDate.java
  be/src/main/java/ssafy/antalbum/entity/photo/PhotoPath.java
  be/src/main/java/ssafy/antalbum/repository/TravelRepository.java
  be/src/main/java/ssafy/antalbum/service/AmazonS3Service.java
  be/src/main/java/ssafy/antalbum/service/TravelService.java
Labels: ✨ Feat

#39 여행 상세보기 -> 태그된 친구 프로필 띄우기 기능
  be/src/main/java/ssafy/antalbum/dto/FriendDto.java
  be/src/main/java/ssafy/antalbum/repository/TravelRepository.java
Labels: ✨ Feat
